spring:
  profiles:
    active: deleteMe
app:
  logging:
    host: 192.168.6.182:5000
logging:
  level:
    br:
      com:
        ithappens:
          mapper: DEBUG

---
# Coloque aqui suas configurações de Desenvolvimento
spring:
  profiles: dev

---
# Coloque aqui suas configurações de Homologação
spring:
  profiles: homo

---
spring:
  profiles: deleteMe
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/treinamento
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

